### ISSUE TITLE
Android handleNotification method for FCM

### ISSUE THREAD

**Issue by Rehubbard** [carnivalmobile/carnival-sdk-react-native#37]
My react-native app implements it's own Firebase onMessage listener. This intercepts the message sent from SailThru on Android. I see nothing in the react-native docs about this, but I found some info in the Android Sailthru docs: https://docs.mobile.sailthru.com/docs/android-integration

Basically, it mentions passing the data message through to the SDK's handler by calling the `handleNotification` method. I would expect to be able to do this `Carnival.handleNotification(message)` in my app's Firebase onMessage handler. But this does not work because handleNotification does not exist. Any ideas?

**Comment by igstewart3** [comment]
Hi @Rehubbard, the React Native SDK doesn't have a `handleNotification` method because the notification handling is all done at the native level. If you are receiving the message in React Native it seems likely another library is catching these details natively and passing them up to your app. It's possible this is what is causing issues for our SDKs (which would normally handle these messages automatically).
To fix this you may need to turn off auto integration on iOS (details [here](https://docs.mobile.sailthru.com/docs/ios-auto-integration)), and implement the FirebaseMessagingService in your native Android app (details [here](https://docs.mobile.sailthru.com/docs/android-integration#section-firebasemessagingservice-implementation)).
This will allow you to pass the SDK the notifications and tokens manually. This could also interfere with the library you are using to pass the details to the React Native level (particularly on the Android side) so you may need to check their documentation to see if they have similar manual workarounds.
