### ISSUE TITLE
App will not reload: null is not an object (evaluating 'Carnival')

### ISSUE THREAD

**Issue by ccorneliusHsv** [carnivalmobile/carnival-sdk-react-native#39]
Getting this error every time I try to reload on iOS. Works every time on a fresh run. But can't use reload.  Using RN version 0.59.5.

![Screen Shot 2019-10-24 at 2 13 26 PM](https://user-images.githubusercontent.com/48597044/67517852-1ffa3100-f669-11e9-9253-8950c8514067.png)

**Comment by ccorneliusHsv** [comment]
Just wanted to clarify that this is running on an Emulator and I'm using command+R.

**Comment by ccorneliusHsv** [comment]
Got a similar error but slightly different. Posting just in case it's related and helpful. 


<img width="389" alt="Screen Shot 2019-10-29 at 12 37 24 PM" src="https://user-images.githubusercontent.com/48597044/67796174-83130b80-fa4d-11e9-85d6-d1bd51f57dfe.png">

**Comment by igstewart3** [comment]
Sorry to hear you're having some issues, let's see what we can do about them. This error seems to occur when an instance of the `RNCarnival` class is not returned properly in the `RCTBridgeDelegate extraModulesForBridge:` method. Can you add a breakpoint into this method and confirm that it is called each time you refresh, and that a new instance of `RNCarnival` is being returned? If you are using the `RNCarnivalBridge` class then the method will be implemented there, otherwise it will be found wherever you have implemented the `RCTBridgeDelegate`.

**Comment by Iyoss** [comment]
Hi @igstewart3, thanks for your reply.
I added a breakpoint to `RNCarnivalBridge` class when I create a `moduleInitialiser`, but it is called once only when I build an application.
```swift
// AppDelegate.swift

func application(_ application: UIApplication,
  didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
) -> Bool {
  . . .

  let jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(
    forBundleRoot: "index",
    fallbackResource: nil
  );

  let moduleInitialiser = RNCarnivalBridge(      // <--- breakpoint here
    jsCodeLocation: jsCodeLocation,
    appKey: sailthruSDKKey
  );
  let bridge = RCTBridge(delegate: moduleInitialiser, launchOptions: launchOptions);
  let rootView = RCTRootView(
    bridge: bridge,
    moduleName: "moduleName", 
    nitialProperties: nil
  );

  . . .
}
```

**Comment by igstewart3** [comment]
Hi @lyoss, sorry if I was unclear, could you put the breakpoint inside the RNCarnivalBridge.m class:

**Comment by Iyoss** [comment]
@igstewart3. The method is called only once.

**Comment by igstewart3** [comment]
OK, so the reason that the 'Carnival' object is null is because it's not being returned from the Bridge Delegate when it should be. Is it possible that the `moduleInitialiser` instance is being lost somewhere? Could you try keeping a strong reference to it in your AppDelegate and then check if the `extraModulesForBridge:` method is called again?

**Comment by Iyoss** [comment]
@igstewart3, thanks. I've created a strong reference and it helped.

**Comment by igstewart3** [comment]
Great! Glad we were able to resolve that.

**Comment by ccorneliusHsv** [comment]
@igstewart3 I was wondering if I could get some guidance on how to create that strong reference.

**Comment by igstewart3** [comment]
@ccorneliusHsv sure, instead of creating the moduleInitialiser as a local variable in the `didFinishLaunchingWithOptions` method like so:
```
let moduleInitialiser = RNCarnivalBridge(
    jsCodeLocation: jsCodeLocation,
    appKey: sailthruSDKKey
  );
```

Declare it as a variable in the AppDelegate and then just assign it in the method:
```
class AppDelegate
var moduleInitialiser : RNCarnivalBridge?
...
func application(_ application: UIApplication,
  didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
) -> Bool {
...
    moduleInitialiser = RNCarnivalBridge(
    jsCodeLocation: jsCodeLocation,
    appKey: sailthruSDKKey
  );
...
}
```
The AppDelegate class will then hold the reference to the moduleInitialiser object.
